
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/invitation
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: invitation:spring:session
  redis:
    host: localhost

logging:
  file:
    name: invitation.log
  level:
    org.springframework.data.mongodb: DEBUG

management:
  endpoints:
    web:
      base-path: /invitation/actuator
